name: test
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python=3.7
  - cudatoolkit=11.0
  - pytorch=1.7
  - torchvision=0.8.0
  - pip=20.2.4
  - opencv=3.4.2
  - albumentations=0.5.2
  - cruft=2.8.0
  - dvc=2.1.0
  - fire=0.4.0
  - loguru=0.5.3
  - pydantic=1.6.1
  - pre-commit=2.12.1
  - mlflow=1.16.0
  - pytest=6.1.1
  - scikit-learn=0.23.2
  - seaborn=0.11.0
  - plotly=4.11.0
  - cookiecutter=1.7.2
  - torch-model-archiver=0.3.1
  - yacs
  - progressbar
  - pip:
    - torch-dct
    - mmcv-full==1.3.3 -f https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.0/index.html
    - mmsegmentation==0.13.0
